server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/your-username/your-config-repo
          default-label: main
          search-paths: '{application}'
          clone-on-start: true
        # 로컬 저장소를 사용하려면 아래 설정 활성화
        # native:
        #   search-locations: file:///path/to/local/config-repo

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS